/*
**
 * Author:  EUTUXIA
 * Created: 30/04/2020
 */

CREATE DATABASE SERVIELECTRA;

USE SERVIELECTRA;

-- CREACION DE TABLAS

CREATE TABLE CATEGORIAS(
    IDCATEGORIA INT AUTO_INCREMENT,
    CATEGORIA VARCHAR(30),
    
    PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE CONFIGURACION(
    ID INT AUTO_INCREMENT,
    ATRIBUTO VARCHAR(30),
    VALOR VARCHAR(255),
    
    PRIMARY KEY (ID)
);
CREATE TABLE IMAGENESBANNER(
    IDBANNER INT AUTO_INCREMENT,
    IMAGEN VARCHAR(255),
    TITULO VARCHAR(25),
    RESUMEN VARCHAR(180),
    NOMBREBOTON VARCHAR(25),
    URLBOTON VARCHAR(255),
    TIPO int(11),
    PRIMARY KEY (IDBANNER),
    UNIQUE (TIPO)
);
CREATE TABLE PRODUCTOS(
    IDPRODUCTO INT AUTO_INCREMENT,
    TITULO VARCHAR(255),
    DESCRIPCION TEXT,
    IDCATEGORIA INT,
    CARACTERISTICAS TEXT,
    APLICACIONES TEXT,
    VENTAJAS TEXT,
    IMAGEN TEXT,

    PRIMARY KEY (IDPRODUCTO)
);

CREATE TABLE IF NOT EXISTS ARTICLESBLOG(
  IDARTICULO INT AUTO_INCREMENT,
  TITLE varchar(255),
  IMAGE varchar(255),
  DESCRIPTION text,
  CONTENT text,
  KEYWORDS varchar(255),
  AUTOR varchar(255),
  IDCATEGORIA INT,
  DATE TIMESTAMP,

   PRIMARY KEY (IDARTICULO),
   UNIQUE (TITLE)
);

CREATE TABLE USUARIOS(
    IDUSUARIO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(25),
    CORREO VARCHAR(30),
    CLAVE VARCHAR(50),
    NIVEL  INT,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (IDUSUARIO),
    UNIQUE (CORREO)
);
CREATE TABLE SUSCRIPTORES(
    IDSUSCRIPTOR INT AUTO_INCREMENT,
    CORREO VARCHAR(100),
    PRIMARY KEY (IDSUSCRIPTOR),
    UNIQUE (CORREO)
);
CREATE TABLE MENSAJESBLOG(
    IDMENSAJE INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TEXTO TEXT,
    ARTICULOID INT,
    CORREO VARCHAR(100),
    DATE TIMESTAMP,

    PRIMARY KEY (IDMENSAJE)
);