/*
**
 * Author:  EUTUXIA
 * Created: 30/04/2020
 */

CREATE DATABASE SERVIELECTRA;

USE SERVIELECTRA;

-- CREACION DE TABLAS

CREATE TABLE CATEGORIAS(
    IDCATEGORIA INT AUTO_INCREMENT,
    CATEGORIA VARCHAR(30),
    
    PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE CONFIGURACION(
    ID INT AUTO_INCREMENT,
    ATRIBUTO VARCHAR(30),
    VALOR VARCHAR(255),
    
    PRIMARY KEY (ID)
);
CREATE TABLE IMAGENES(
    IDIMAGEN INT AUTO_INCREMENT,
    URLIMAGEN VARCHAR(255),
    TIPO int(11),
    
    PRIMARY KEY (IDIMAGEN)
);
CREATE TABLE PRODUCTOS(
    IDPRODUCTO INT AUTO_INCREMENT,
    TITULO VARCHAR(255),
    DESCRIPCION TEXT,
    IDCATEGORIA INT,
    PRECIO INT,
    IMAGEN TEXT,

    PRIMARY KEY (IDPRODUCTO)
);

CREATE TABLE IF NOT EXISTS ARTICLESBLOG(
  IDARTICULO INT AUTO_INCREMENT,
  TITLE varchar(255),
  IMAGE varchar(255),
  DESCRIPTION text,
  CONTENT text,
  KEYWORDS varchar(255),
  AUTOR varchar(255),
  DATE TIMESTAMP,

   PRIMARY KEY (IDARTICULO),
   UNIQUE (TITLE)
);

CREATE TABLE USUARIOS(
    IDUSUARIO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(25),
    CORREO VARCHAR(30),
    CLAVE VARCHAR(50),
    NIVEL  INT,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (IDUSUARIO),
    UNIQUE (CORREO)
)